const Actions = {
	LOGIN: 'DO_LOGIN',
	DIDLOGIN: 'DID_LOGIN',
	LOGOUT: 'LOGOUT',
	GETOFFER: 'GET_OFFER',
	GETBANKS: 'GET_BANKS',
	GETROUTING: 'GET_ROUTING',
	GETSDK: 'GET_SDK',
	GETPROMO: 'GET_PROMO',
	FETCHING: 'FETCHING',
	VIEWUSERS: 'VIEW_USERS',
	DEFAULT: 'No_CHANGE',
	VIEW_BY_COUNTRY: 'VIEW_BY_COUNTRY',
	VIEW_BY_AIRLINES: 'VIEW_BY_AIRLINES',

	//EMPLOYEE
	GET_ATTRIBUTES: 'GET_EMP_ATTRIBUTES',

	//Common Mdata
	VIEW: 'fetch_data',
	ADD: 'add_data',
	EDIT: 'view_data',
	DELETE: 'delete_data',
	DISMISS: 'dismiss_alert',

	//Task
	VIEW_TASK_UtiLITY: 'VIEW_TASK_UTILITY',
	ADD_TASK: 'ADD_TASK',

	VIEW_CLIENT_REGIONS: 'VIEW_CLIENT_REGIONS',
	ADD_CLIENT: 'ADD_CLIENTS',
	DELETE_CLIENT: 'DELETE_CLIENT',

	VIEW_DESIGNATIONS: 'VIEW_DESIGNATIONS',
	ADD_DESIGNATION: 'ADD_DESIGNATION',
	DELETE_DESIGNATION: 'DELETE_DESIGNATION',
	
	VIEW_POLICY: 'VIEW_POLICY',
	ADD_POLICY: 'ADD_POLICY',
	DELETE_POLICY: 'DELETE_POLICY',

	VIEW_REGIONS: 'VIEW_REGION',
	ADD_REGION: 'ADD_REGION',
	DELETE_REGION: 'DELETE_REGION'


};

export default Actions;
